version: "3.6"

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./Persistence/KassaDG.db:/Persistence/KassaDG.db
      - ./Persistence/KassaDG.db.clean:/Persistence/KassaDG.db.clean
    ports:
    - 5002:80