version: "3.6"

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
#    volumes:
#      - ./Persistence/KassaDG.db:/Persistence/KassaDG.db
#      - ./Persistence/KassaDG.db.clean:/Persistence/KassaDG.db.clean
    ports:
    - 5000:80
    environment:
      AllowedOrigins: "http://localhost:5000;http://localhost:4200"
      BackupCountRollover: 100
      DATABASE_CAN_BE_RESET: "true"