name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: docker-netcore-cache-{hash}
          restore-keys: |
            docker-netcore-cache-
      - name: Build Docker image
        run: docker-compose build
      - name: Start Application
        run: docker-compose up -d
      - name: Copy clean db
        uses: canastro/copy-file-action@master
        with:
          source: ./Persistence/KassaDG.db.clean
          target: ./Persistence/KassaDG.db
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: End2EndTests
          browser: chrome
          wait-on: 'http://localhost:5002'
          record: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
