name: .NET Core

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker-compose build
      - name: Start Application
        run: docker-compose up -d
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: End2EndTests
          browser: chrome
          wait-on: 'http://localhost:5000'
          record: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
