name: .NET Core

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: docker-netcore-cache-[3]-{hash}
          restore-keys: |
            docker-netcore-cache-[3]-
      - name: Build Docker image
        run: docker-compose build
      - name: Start Application
        run: docker-compose up -d
      - name: Check logs
        run: docker-compose logs
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: End2EndTests
          browser: chrome
          wait-on: 'http://localhost:5000'
          record: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
