name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: SetupEF
      run: dotnet tool install --global dotnet-ef
    - name: SetupCleanDb
      run: cd Persistence && dotnet ef database update && cp KassaDG.db KassaDG.db.clean
    - name: SetupSettingsFile
      run: 'echo "$APP_SETTINGS" > KassaDG/bin/Release/netcoreapp3.1/appsettings.json && mkdir KassaDG/bin/Release/netcoreapp3.1/token.json && echo "$DRIVE_TOKEN" > KassaDG/bin/Release/netcoreapp3.1/token.json/Google.Apis.Auth.OAuth2.Responses.TokenResponse-user'
      shell: bash
      env:
        APP_SETTINGS: ${{secrets.APP_SETTINGS}}
        DRIVE_TOKEN: ${{secrets.DRIVE_TOKEN}}
    - name: MarkServerExecutable
      run: chmod +x KassaDG/bin/Release/netcoreapp3.1/KassaDG
    - name: End2EndTest
      uses: cypress-io/github-action@v2
      with:
        start: '../KassaDG/bin/Release/netcoreapp3.1/KassaDG'
        browser: chrome
        working-directory: 'End2EndTests'
        wait-on: 'http://localhost:5000'
        wait-on-timeout: 60
      env:
        CLEAN_DB: '../Persistence/KassaDG.db.clean'
        TARGET_DB: '../Persistence/KassaDG.db'